services:
  - type: web
    name: satellite-tracker-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: N2YO_API_KEY
        sync: false # You'll set this in Render dashboard