services:
  - type: web
    name: satellite-tracker-backend
    env: node
    rootDir: ./server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: N2YO_API_KEY
        sync: false # You'll set this in Render dashboard